### ISSUE TITLE
New Website Logo: Stratis Storage

### ISSUE THREAD

**Issue by agrover** [rust-lang/prev.rust-lang.org#1067]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: Stratis Storage
- Homepage url: https://stratis-storage.github.io/
- Logo url: https://stratis-storage.github.io/stratis_CMYK_grey.jpg
- How you are using Rust: stratisd daemon is written in Rust.
- Url describing Rust usage: (optional link to e.g. blog post explaining how you use Rust) sorry don't have one
- Organization contact: Andy Grover agrover@redhat.com

**Comment by agrover** [comment]
OK understood.

This is a project started by Red Hat. Should we be asking for that logo to be added instead?

**Comment by steveklabnik** [comment]
I think it's a bit complicated for projects like this; in some sense, this is a product, which we do accept logos for; the fact that it's OSS is incidental to the fact that Red Hat's products are open source.

I'd be okay with the stratis logo, personally, but a Red Hat one would be even better, of course, hehe.

@aturon is at a thing this week and so isn't likely to be able to respond until next. @rust-lang/core opinions here?

**Comment by mulkieran** [comment]
@aturon Could you let us know what you think?

**Comment by mulkieran** [comment]
@aturon, @steveklabnik, should we close this?

**Comment by mati865** [comment]
@agrover @mulkieran this repository is deprecated, new version is hosted at https://github.com/rust-lang/www.rust-lang.org
That's how it looks like: https://www.rust-lang.org/production/users

**Comment by mulkieran** [comment]
Ok. Redirected! Please go ahead and close this one.
