### ISSUE TITLE
doc.rust-lang.org: sort the method names

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/prev.rust-lang.org#1186]
I don't know where to put this issue, this is likely not the right repository.

Method names like in https://doc.rust-lang.org/std/collections/struct.HashMap.html are presented on the left hand side in arbitrary order. This makes it very hard to browse.

**Comment by Deedasmi** [comment]
This is a cargo issue, but I'd recommend opening an issue in [doxidize](https://github.com/steveklabnik/doxidize), which will end eventually replace cargo doc

**Comment by kud1ing** [comment]
I've read somewhere that at least for modules there is an option whether to sort or not.
So i am not sure whether this issue here is about "adding this option to the code" or "using that option".

**Comment by kud1ing** [comment]
The method names are sorted now.
